name: book_net
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  dio: ^4.0.0
  flutter_screenutil: ^5.3.1
  flutter_svg: ^0.23.0+1
  intl: ^0.17.0
  google_fonts: ^2.1.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  animated_splash_screen: ^1.2.0
  

  #Http
  http: ^0.13.0

  #Realtime
  socket_io_client: ^1.0.1
  form_field_validator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SegoeUI
      fonts:
        - asset: fonts/Segoe-UI.ttf
        - asset: fonts/Segoe-UI-Medium.ttf
          weight: 300
        - asset: fonts/Segoe-UI-Italic.ttf
          style: italic
        - asset: fonts/Segoe-UI-Bold.ttf
          weight: 600
        - asset: fonts/Segoe-UI-Bold-Italic.ttf
          weight: 600
          style: italic

